# Generated by Django 5.2 on 2025-04-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starfall_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='video_url',
        ),
        migrations.AddField(
            model_name='song',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='song_videos/'),
        ),
    ]
